### ISSUE TITLE
App crash when Belote score is empty

### ISSUE THREAD

**Issue by marwendoukh** [Binary-Team/Rachma-Android#22]
The app crashes when the user save the score and the score input is empty.

**Comment by mohamedamineznaidi** [comment]
@marwendoukh 
![screenshot_20170815-134914](https://user-images.githubusercontent.com/27930067/29316638-a7708cbc-81c0-11e7-8287-d013020496d3.png)

**Comment by marwendoukh** [comment]
@mohamedamineznaidi  I could reproduce this issue on my Samsung Android device (version 4.4) .

**Steps to reproduce** 
1. Set a Belote game with all the default values
2. Save the score with an empty input.

The app will crash , please see the screenshot below .


![photo5807707043564464747](https://user-images.githubusercontent.com/10298519/29317082-51f4b3d8-81c2-11e7-8c99-ca2677ecf8aa.jpg)

**Comment by mohamedamineznaidi** [comment]
Yes @marwendoukh when I switched my phone language to English, I have had the same bug, I think that I have a problem in the translation of Strings, thx, it will be resolved very soon

**Comment by mohamedamineznaidi** [comment]
@marwendoukh is everything alright now ?

**Comment by marwendoukh** [comment]
LGTM
