### ISSUE TITLE
Add Material design components

### ISSUE THREAD

**Issue by marwendoukh** [Binary-Team/Rachma-Android#24]
Add material design components to the App .

**Comment by mohamedamineznaidi** [comment]
Dear @marwendoukh , Thanks for the for the job you where doing it was AWESOME :D , i'am so sorry i was busy those days !
I have some feedback about the new design of our application,
First i found that showing the name of application on the top of the screen is useless ,user knows that he is using rachma so we dont have to inform him on every page , also i found that we are losing space in the screen espicially when user is using small screen phone.

For how the application looks , my first impression was "ohh it was more beautiful with the old design" especially at the first menu it's not attractive at all , it doesn't make you exited to discover the application.
So we Have a lot of work to do on the design of the application , for me it's one of the most important things that can lead our application to success , you know that users are addicted to the awesome things that they see's so we must make our application like a trap , when it's open you most have these feeling "I want to play cards NOW !"
And finally i want to Re-thank you again for the great the job that you are doing , i am so happy to collaborate with you maybe it's a little project but i am sure that we will make great things together.

**Comment by marwendoukh** [comment]
No problem , we will discuss this in our next meeting (later this week) .

**Comment by marwendoukh** [comment]
Separated issues have been created for all the things that needs improvement. 
I'll close this issue
